version: '3.9' # Recommended version for modern features

services:
  gitlab-runner:
    # 1. Image
    image: gitlab/gitlab-runner:latest
    
    # 2. Container Name
    container_name: gitlab-runner
    
    # 3. Restart Policy
    restart: always
    
    # 4. Volumes (Bind Mounts)
    volumes:
      # Mount the Docker socket to allow the runner to run Docker-in-Docker (dind)
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Mount the configuration directory for persistent configuration
      - /srv/gitlab-runner/config:/etc/gitlab-runner
    
    # 5. Hostname Mapping (Equivalent of --add-host)
    # This adds an entry to the container's /etc/hosts file, ensuring 
    # the runner can resolve gitlab.mdx.local to the specified IP.
    extra_hosts:
      - "gitlab.mdx.local:IP"
